services:
  mysql-dev-server:
    image: mysql/mysql-server:5.7
    restart: always
    environment:
      - MYSQL_DATABASE
      # So you don't have to use root, but you can if you like
      - MYSQL_USER
      # You can use whatever password you like
      - MYSQL_PASSWORD
      # Password for root access
      - MYSQL_ROOT_PASSWORD
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - "${MYSQL_PORT-9002}:3306"
    expose:
      # Opens port 3306 on the container
      - "3306"
      # Where our data will be persisted
    volumes:
      - mysqldb:/var/lib/mysql
  postgres-dev-server:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB
      # So you don't have to use root, but you can if you like
      - POSTGRES_USER
      # You can use whatever password you like
      - POSTGRES_PASSWORD
    ports:
      # <Port exposed> : < POSTGRES Port running inside container>
      - "${POSTGRES_PORT-9003}:5432"
    expose:
      # Opens port 5432 on the container
      - "5432"
      # Where our data will be persisted
    volumes:
      - postgresdb:/var/lib/postgresql/data
# Names our volume
volumes:
  mysqldb:
  postgresdb:
