services:
  mysql:
    container_name: mysql8_dev
    command: --sql_mode="STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION"
    image: mysql/mysql-server:8.0
    restart: always
    environment:
      - MYSQL_DATABASE
      # So you don't have to use root, but you can if you like
      - MYSQL_USER
      # You can use whatever password you like
      - MYSQL_PASSWORD
      # Password for root access
      - MYSQL_ROOT_PASSWORD
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - "${MYSQL8_PORT}:3306"
    expose:
      # Opens port 3306 on the container
      - "3306"
      # Where our data will be persisted
    volumes:
      - mysql8db:/var/lib/mysql
# Names our volume
volumes:
  mysql8db:
