services:
  db:
    container_name: postgres_dev
    image: postgres:13.6
    restart: always
    environment:
      - POSTGRES_DB
      # So you don't have to use root, but you can if you like
      - POSTGRES_USER
      # You can use whatever password you like
      - POSTGRES_PASSWORD
    ports:
      # <Port exposed> : < POSTGRES Port running inside container>
      - "${POSTGRES_PORT}:5432"
    expose:
      # Opens port 5432 on the container
      - "5432"
      # Where our data will be persisted
    volumes:
      - postgresdb:/var/lib/postgresql/data
# Names our volume
volumes:
  postgresdb:
